import 'package:weather_app/data/const/enums.dart';

import 'all_keys.dart';

Map<String, String> ar = {
  CustomTrans.login: "تسجيل الدخول",
  CustomTrans.createANewAccount: "انشاء حساب جديد",
  CustomTrans.createNewAccount: "أنشئ حساب جديد",
  CustomTrans.welcomeLine: "يجب عليك التسجيل لاستخدام التطبيق",
  CustomTrans.welcome: "مرحبا",
  CustomTrans.phone: 'رقم الهاتف',
  CustomTrans.write: "إكتب",
  CustomTrans.password: "كلمة المرور",
  CustomTrans.forgotYourPassword: "هل نسيت كلمة السر؟",
  CustomTrans.youDontHaveAnAccount: "ليس لديك حساب ؟",
  CustomTrans.alreadyHaveAnAccount: "لديك حساب بالفعل؟",
  CustomTrans.send: "إرسال",
  CustomTrans.forgetScreenLine:
      "لا تقلق, ما عليك سوي كتابة رقم هاتفك وسنرسل لك رمز التحقق",
  CustomTrans.orBy: "او من خلال",
  CustomTrans.codeVerification: "التحقق من الرمز",
  CustomTrans.otpScreenLine: "ادخل الرمز الذي تم ارساله الي رقم هاتفك",
  CustomTrans.editPhoneNumber: "تعديل الرقم",
  CustomTrans.resendMsg: "إعادة ارسال الرمز",
  CustomTrans.confirmPassword: "تاكيد كلمة السر",
  CustomTrans.crateNewPasswordScreenLine:
      "أكتب كلمة المرور الجديدة لتسجيل الدخول",
  CustomTrans.crateNewPassword: "انشاء كلمة مرور جديدة",
  CustomTrans.choose: "إختر",
  CustomTrans.affiliateType: "نوع الافيليت",
  CustomTrans.next: "التالى",
  CustomTrans.governorate: "المحافظة",
  CustomTrans.city: "المدينة",
  CustomTrans.productPromotionMethod: "طريقة ترويجك للمنتجات",
  CustomTrans.dateOfBirth: "تاريخ الميلاد",
  CustomTrans.address: "العنوان",
  CustomTrans.yourWebsite: "موقعك الشخصي",
  CustomTrans.iDontHaveAPersonalWebsite: "لا يوجد لدي موقع شخصي",
  CustomTrans.iAgreeToAffiliateProgram:
      "اوافق على برنامج المسوق بالعمولة الخاص بـ ",
  CustomTrans.termsAndConditions: "الشروط والأحكام",
  CustomTrans.name: "الإسم",
  CustomTrans.fullName: "الإسم بالكامل",
  CustomTrans.cancel: "إلغاء",
  CustomTrans.yourDataHasBeenSuccessfullyModified: "تم تعديل بياناتك بنجاح",
  CustomTrans.backToMain: "عودة إلى الصفحة الرئيسية",
  CustomTrans.passwordChangedSuccessfully: "تم تغيير كلمة المرور بنجاح",
  CustomTrans.areYouSureYouWantToLogout: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  CustomTrans.signOut: "تسجيل الخروج",
  CustomTrans.successOperation: "تمت العمليه بنجاح",
  CustomTrans.goMainPage: "الذهاب الي الرئيسيه",
  CustomTrans.somethingWentWrong: 'شيء ما حدث بشكل خاطئ',
  CustomTrans.internalServerError: 'خطأ في السبرفر',
  CustomTrans.badRequest: 'خطأ في الطلب',
  CustomTrans.requestToAPIServerWasCancelled: 'تم إلغاء الطلب إلى خادم API',
  CustomTrans.connectionTimeoutWithAPIServer: 'برجاء التحقق من الانترنت',
  CustomTrans.connectionToAPIServerFailedDueToInternetConnection:
      'فشل الاتصال بالسيرفر بسبب الاتصال بالإنترنت',
  CustomTrans.receiveTimeoutInConnectionWithAPIServer:
      'برجاء التحقق من الانترنت',
  CustomTrans.sendTimeoutInConnectionWithAPIServer: 'برجاء التحقق من الانترنت',
  CustomTrans.resendCode: 'إعادة ارسال الرمز',
  CustomTrans.fixedCommission: "عمولة ثابتة",
  CustomTrans.freeCommission: "عمولة حره",
  CustomTrans.web: 'موقع إلكترونى',
  CustomTrans.facebook: 'فيس بوك',
  CustomTrans.twitter: 'تويتر',
  CustomTrans.instagram: 'إنستجرام',
  CustomTrans.pinIsIncorrect: 'الكود غير صحيح',
  CustomTrans.mustHaveValue: 'يجب أن يكون لها قيمة',
  CustomTrans.wrongNumber: 'رقم غير صحيح',
  CustomTrans.wrongConfirmedPassword: 'كلمة مرور مؤكدة خاطئة',
  CustomTrans.youMustChooseTheProvinceFirst: "لابد من إختيار المحافظة أولا",
  CustomTrans.wrongEmail: "بريد الكترونى خاطئي",
  CustomTrans.email: "بريد الكترونى",
  CustomTrans.wrongWebSite: 'موقع خاطئ',
  CustomTrans.writePassword: 'من  فضلك  ادخل  كلمه السر',
  CustomTrans.writeName: 'من فضلك ادخل الاسم',
  CustomTrans.writePhone: ' من فضلك  ادخل رقم الهاتف ',
  CustomTrans.showAll: 'عرض الكل ',
  CustomTrans.addToCart: 'اضف الي عربة التسوق',
  CustomTrans.price: 'السعر',
  CustomTrans.commission: 'العمولة',
  CustomTrans.writeDate: "اختر تاريخ ميلادك",
  CustomTrans.youMustChoose: "بحاجة إلى الاختيار",
  CustomTrans.pleaseWrite: 'أكتب رجاءا',
  CustomTrans.goTo: 'الذهاب الى',
  CustomTrans.needToSignUpFirst: 'بحاجة للتسجيل أولا',
  CustomTrans.mustChoose: ' من فضلك إختر',
  CustomTrans.mustWrite: ' من فضلك إكتب',
  CustomTrans.notification: 'الاشعارات',
  CustomTrans.confirm: "تاكيد",
  CustomTrans.save: "حفظ",
  CustomTrans.favorite: 'المفضلة',
  CustomTrans.payment: 'الدفع',
  CustomTrans.home: 'الرئيسية',
  CustomTrans.myOrder: 'طلباتي',
  CustomTrans.setting: 'الاعدادات',
  CustomTrans.myProduct: 'منتجاتي',
  CustomTrans.buyWhenDeliveredCash: "اشتر عند التسليم نقدًا",
  CustomTrans.buyWithCreditCard: "اشتر ببطاقة الائتمان",
  CustomTrans.buyWithVodafoneCashWallet: "الشراء باستخدام محفظة فودافون",
  CustomTrans.supportCenter: "مركز الدعم",
  CustomTrans.availableNow: "متاح الأن",
  CustomTrans.language: 'لغة',
  CustomTrans.categories: 'الأقسام',
  CustomTrans.marks: 'الماركات',
  CustomTrans.whatDoYouSearchFor: 'ما الذي تبحث عنه ؟',
  CustomTrans.chooseTheItinerary: "اختر خط السير",
  CustomTrans.notehasUploaded: "تم تسجيل الملاحظات",
  CustomTrans.writeNotes: "اكتب الملحوظات",
  CustomTrans.sendingNotes: "ارسال الملاحظات",
  CustomTrans.createItinerary: "اختيار خط سير",
  CustomTrans.createPlan: "انشاء خطة",
  CustomTrans.dailyReport: "التقرير اليومي",
  CustomTrans.weeklyReport: "التقرير الاسبوعي",
  CustomTrans.monthlyReport: "التقرير الشهري",
  CustomTrans.annualReport: "التقرير السنوي",
  CustomTrans.achieved: "قيد الموافقة",
  CustomTrans.bills: "الفواتير",
  CustomTrans.receiveNotifications: "استقبال الاشعارات",
  CustomTrans.chooseAddress: "اختيار عنوان اساسي",
  CustomTrans.listClientAddress: "عناوين العميل",
  CustomTrans.addNewLOCATION: "اضافة عنوان جديد",
  CustomTrans.multipleLocationOptions: "اختيارات تعدد الاماكن",
  CustomTrans.confirmReceiptOfThePayment: "تأكيد استلام المبلغ",
  CustomTrans.typeOfVisit: "نوع الزيارة",
  CustomTrans.visit: "زيارة",
  CustomTrans.inventory: "جرد مخزن",
  CustomTrans.chooseTypeOfVisit: "إختر نوع الزيارة",
  CustomTrans.addExpenses: "أضف نفقة",
  CustomTrans.reason: "السبب",
  CustomTrans.chooseClientsFirst: "اختر العملاء اولا",
  CustomTrans.numberComplete: "اكتمل العدد",
  CustomTrans.thisDayIsaVacation: "هذا اليوم أجازة",
  CustomTrans.controlBoard: "لوحة التحكم",
  CustomTrans.expenses: "النفقات",
  CustomTrans.installment: "القسط",
  CustomTrans.chooseProductsFirst: "اختر المنتجات اولا",
  CustomTrans.complete: "إتمام",
  CustomTrans.chooseReasonFirst: "اختر السبب اولا",
  CustomTrans.collected: "تم التحصيل",
  CustomTrans.successfullyVisited: "تمت الزيارة بنجاح",
  CustomTrans.thereIsNoAchievement: "لا يوجد تحصيل",
  CustomTrans.theClientIsNotAvailable: "العميل غير متواجد",
  CustomTrans.chooseReason: "اختر السبب",
  CustomTrans.areYouSureYouWantToEndTask:
      "هل أنت متأكد أنك تريد انهاء الزيارة ؟",
  CustomTrans.arEG: "ar-SA",
  CustomTrans.chooseDateFirst: "أدخل التاريخ اولا",
  CustomTrans.whyDoYouWantToPostponeTheVisitNow:
      "لماذا تريد تأجيل الزيارة الان ؟",
  CustomTrans.productMarketing: "تسويق المنتجات",
  CustomTrans.arrive: "تم الوصول",
  CustomTrans.addReturns: "اضافة مرتجع",
  CustomTrans.addOrder: "اضافة طلب",
  CustomTrans.addOperation: "اضافة عملية",
  CustomTrans.doYouWantToStartTaskNow: "هل تريد بدء الزيارة الان ؟",
  CustomTrans.companyDecisions: "قرارات الشركة",
  CustomTrans.toyourCurrentLocation: "الي عنوانك الحالي",
  CustomTrans.doYouWantChangeClientLocation: "هل تريد تغير عنوان",
  CustomTrans.cancelTask: "الغاء الزيارة",
  CustomTrans.august: "اغسطس",
  CustomTrans.july: "يوليو",
  CustomTrans.june: "يونيه",
  CustomTrans.may: "مايو",
  CustomTrans.april: "ابريل",
  CustomTrans.march: "مارس",
  CustomTrans.february: "فبراير",
  CustomTrans.january: "يناير",
  CustomTrans.orders: "الطلبات",
  CustomTrans.returns: "قائمة المرتجعات",
  CustomTrans.notes: "الملحوظات",
  CustomTrans.pending: "قيد الإنتظار",
  CustomTrans.inProgress: "قيد التنفيذ",
  CustomTrans.completed: "مكتملة",
  CustomTrans.chooseGovernmentFirst: "اختر المحافظة اولا",
  CustomTrans.chooseCity: "إختر المدينة",
  CustomTrans.clientType: "نوع العميل",
  CustomTrans.enterYourMobileNumberAndWeWillSendYouaCode: "ادخل موبايل",
  CustomTrans.writePhoneNumber: "يجب كتابة رقم موبايل",
  CustomTrans.noData: "لا يوجد بيانات",
  CustomTrans.foundNoData: "لا يوجد بيانات",
  CustomTrans.installments: "الاقساط",
  CustomTrans.clientName: "اسم العميل",
  CustomTrans.reTurn: "ارجاع",
  CustomTrans.pleaseChooseProductsYouWantToReturnAndTheWayOfReturns:
      "اختر المنتجات المراد ارجاعها و طريقة الارجاع",
  CustomTrans.areYouSureYouWantToReturnTheseProducts:
      "هل انت متاكد من ارجاع تلك المنتجات",
  CustomTrans.numberOfMonths: "عدد الأشهر",
  CustomTrans.numberOfInstallments: "عدد القساط",
  CustomTrans.clientList: "قائٍمة العملاء",
  CustomTrans.errorTryConnectAgain: "حدث خطأ كرر المحاولة",
  CustomTrans.pleaseChooseClient: "من فضلك إختر إسم العميل",
  CustomTrans.enterNewDate: "أدخل الميعاد الجديد",
  CustomTrans.enterReason: "ادخل السبب",
  CustomTrans.whyYouWantCancelVisitNow: "لماذا تريد الغاء الزيارة الان ؟",
  CustomTrans.needToChooseClientFirst: "يجب اختيار اسم العميل اولا",
  CustomTrans.cashReceipt: "استلام نقدي",
  CustomTrans.newReturn: "مرتجع جديد",
  CustomTrans.newOrder: "طلب جديد",
  CustomTrans.search: "إبحث",
  CustomTrans.startWorkFirst: "ابدأ العمل أولا",
  CustomTrans.chooseGovernmentAndCityFirst: "حدد المحافظة و المدينة اولا",
  CustomTrans.pleaseChooseCity: "من فضلك إختر المدينة",
  CustomTrans.government: "المحافظة",
  CustomTrans.pleaseChooseGovernment: "من فضلك إختر المحافظة",
  CustomTrans.chooseGovernment: "إختر المحافظة",
  CustomTrans.pleaseEnableGpsAndPermissionAlwaysToStartWork:
      "يجب السماح لتحديد الموقع يكون دائم لبدء العمل",
  CustomTrans.workEndSuccessfully: "تم إنهاء العمل بنجاح",
  CustomTrans.productsInfo: "تفاصيل المنتج",
  CustomTrans.removeProductsFromCart: "تم إزالة المنتج من المحتوى",
  CustomTrans.directions: "التوجيهات",
  CustomTrans.packageSize: "حجم العبوة",
  CustomTrans.results: "النتائج",
  CustomTrans.ingredients: "المكونات",
  CustomTrans.doses: "الجرعات",
  CustomTrans.indications: "طريقة الإستخدام",
  CustomTrans.addClient: "إضافة عميل",
  CustomTrans.addVisit: "أضف زيارة",
  CustomTrans.addInvoice: "إستلام نقدية",
  CustomTrans.visits: "الزيارات",
  CustomTrans.store: "المتجر",
  CustomTrans.noNotification: "لا يوجد اشعارات",
  CustomTrans.endWork: "إنهاء العمل",
  CustomTrans.startWork: "بدأ العمل",
  CustomTrans.areYouSureYouWantToCheckOut:
      "هل أنت متأكد أنك تريد إنهاء العمل ؟",
  CustomTrans.areYouSureYouWantToCheckIn: "هل أنت متأكد أنك تريد بدء العمل ؟",
  CustomTrans.createCustomVisits: "إنشاء زيارات مخصصة",
  CustomTrans.createABusinessPlan: "إنشاء زيارات مخصصة",
  CustomTrans.administrativeNotes: "الملحوظات الإدارية",
  CustomTrans.reports: "التقارير",
  CustomTrans.yes: "نعم",
  CustomTrans.no: "لا",
  CustomTrans.areYouSureYouWantToSignOut: "هل انت متاكد انك تريد الخروج ؟",
  CustomTrans.end: "انهاء",
  CustomTrans.passwordNotMatch: "كلمة المرور غير متطابقة",
  CustomTrans.resendMessage: "إعادة ارسال",
  CustomTrans.completeAllFields: "أكمل جميع الخانات",
  CustomTrans.enter4NumbersThatHaveBeenSentToYouOnThis:
      "ادخل 4 ارقام التي تم إرسالها لك على هذا",
  CustomTrans.activationMessage: "رسالة التفعيل",
  CustomTrans.passwordNeedToMixBetweenLettersAndNumbers:
      "كلمة المرور يجب ان تحتوي على مزيج من أرقام و حروف",
  CustomTrans.newPassword: "كلمة مرور جديدة",
  CustomTrans.errorTryAgain: "خطأ في الإتصال حاول مره أخرى",
  CustomTrans.tContinue: "أكمل",
  CustomTrans.signIn: "تسجيل الدخول",
  CustomTrans.andYouCanLogIn: "و تتمكن من تسجيل الدخول",
  CustomTrans.enterYourActivationCodeAndAnActivationCodeWillBeSentToTheAccount:
      "ادخل كود التفعيل الخاص بك وسيتم ارسال كود لتفعيل الأكونت",
  CustomTrans.canNotRememberPassword: "لم تتذكر كلمة المرور",
  CustomTrans.forgotPassword: "نسيت كلمة المرور",
  CustomTrans.pleaseWriteYourPassword: "عفوا يجب كتابة كلمة المرور",
  CustomTrans.loginToGetStartedWithTheAppAndEnjoyAllTheFeartures:
      "يجب عليك تسجيل الدخول لتتمكن من استخدام التطبيق",
  CustomTrans.welcome: "مرحبا بك",
  CustomTrans.enterEmail: "ادخل البريد الإلكتروني",
  CustomTrans.enterName: "ادخل الإسم",
  CustomTrans.needToWriteYourName: "يجب كتابة الاسم",
  CustomTrans.profile: "الصفحة الشخصية",
  CustomTrans.errorConnectionPleaseCheckTheInternetAndTryAgain:
      "خطأ في الاتصال تاكد من الاتصال بالانترنت",
  CustomTrans.changePasswordSuccessfully: "تم تغيير الرقم السري بنجاح",
  CustomTrans.thePasswordDoesNotMatch: "الرقم السري غير متطابق",
  CustomTrans.oldPassword: "كلمة المرور القديمة",
  CustomTrans.settings: "الإعدادات",
  CustomTrans.changePassword: "تغيير كلمة المرور",
  CustomTrans.changeLanguage: "تغيير اللغة",
  CustomTrans.forgetPassword: "نسيت كلمة المرور",
  CustomTrans.newClientInfo: "بيانات عميل جديد",
  CustomTrans.enterClientType: 'اختر نوع العميل',
  CustomTrans.enterClientName: 'اختر اسم العميل',
  CustomTrans.tCase: 'الحالة',
  CustomTrans.unComplete: "غير مكتملة",
  CustomTrans.cash: "كاش",
  CustomTrans.code: 'الكود',
  CustomTrans.quantity: 'الكمية',
  CustomTrans.repName: 'اسم المندوب',
  CustomTrans.history: 'التاريخ',
  CustomTrans.deductionFromDept: ' خصم من المديونيه',
  CustomTrans.merchandiseBalance: 'رصيد بضاعه',
  CustomTrans.cashBalance: 'رصيد كاش',
  CustomTrans.paymentMethod: 'طريقة الدفع',
  CustomTrans.total: 'الحساب الكلي',
  CustomTrans.paid: 'المدفوع',
  CustomTrans.remain: 'المتبقي',
  CustomTrans.totalOrders: "اجمالي الطلبيات",
  CustomTrans.totalOrdersAfter: 'اجمالي الطلبيات بعد التصفية',
  CustomTrans.lE: "ريال",
  CustomTrans.imageNotFound: "الصورة غير موجوده",
  CustomTrans.finished: 'منتهي',
  CustomTrans.started: 'تم البدء',
  CustomTrans.tNew: 'جديد',
  CustomTrans.appointments: 'المواعيد اليومية',
  CustomTrans.cart: 'المتجر',
  CustomTrans.managmentNotes: "الملحوظات الادارية",
  CustomTrans.createWeekelyPlan: 'إنشاء خطة عمل',
  CustomTrans.totalReturns: "اجمالي المرتجعات",
  CustomTrans.lastOrder: 'اخر طلب',
  CustomTrans.lastBill: 'اخر فاتورة',
  CustomTrans.operation: 'نوع العملية',
  CustomTrans.visitPurpose: 'غرض الزيارة',
  CustomTrans.visitSummary: 'ملخص الزيارة',
  CustomTrans.newVisit: 'زيارة جديدة',
  CustomTrans.workStartSuccessfully: "تم بدء العمل بنجاح",
  CustomTrans.totalBills: 'اجمالي الفواتير',
  CustomTrans.pay: 'سداد',
  CustomTrans.payDirectlyToTheRepresentativeByGivingHimPaperMoney:
      'الدفع مباشرة للمندوب عن طريق اعطائه نقود ورقية',
  CustomTrans.paymentByCheck: 'الدفع عن طريق الشيك',
  CustomTrans.writeCheck: 'تحرير شيك بالمبلغ المطلوب',
  CustomTrans.noActionPlanToday: 'لا يوجد خطة عمل اليوم',
  CustomTrans.hide: "اخفاء",
  CustomTrans.totalPrice: 'اجمالي السعر',
  CustomTrans.soldInsurance: 'تم البيع - تأمين',
  CustomTrans.soldInstallment: 'تم البيع - قسط',
  CustomTrans.soldCash: 'تم البيع - كاش',
  CustomTrans.createAnInvoice: "انشاء فاتورة",
  CustomTrans.createAnOrder: "انشاء طلبية",
  CustomTrans.sections: "أقسام",
  CustomTrans.enterTheQuantityYouWantToAddFromThisProduct:
      'ادخل الكمية التي تريد اضافتها من هذا المنتج',
  CustomTrans.endPurchase: 'انهاء عملية الشراء',
  CustomTrans.continueOrder: 'استمرار الطلب',
  CustomTrans.makeANewOrderWithTheAmountOfMoneyOfReturnedProducts:
      'قم بعمل طلب جديد بمبلغ نقود المنتجات المرتجعة',
  CustomTrans.writingAChequeWithTheDemandedAmountOfMoneyAndHandingItToTheRep:
      "تحرير شيك بالمبلغ المطلوب و اعطائه للمندوب",
  CustomTrans.oneTimePayment: "دفعة لمرة واحدة",
  CustomTrans.recieveCashInExchangeOfReturnedProducts:
      'تلقي النقود في مقابل المنتجات المرتجعة',
  CustomTrans.recieveCash: 'تلقي النقود',
  CustomTrans.moneyWillBePaidInFormerDepts:
      'سيتم دفع الأموال في الأقسام السابقة',
  CustomTrans.payFromDept: 'الدفع من المديونية',
  CustomTrans.afterReturn: 'ما بعد الاسترجاع',
  CustomTrans.status: 'الحالة',
  CustomTrans.offers: 'العروض',
  CustomTrans.getDiscount: 'خصم',
  CustomTrans.totalOffer: 'اجمالي الخصم',
  CustomTrans.totalAfter: "الاجمالي بعد الخصم",
  CustomTrans.gifts: 'الهدايا',
  CustomTrans.thereIsNoQuantityInStock: 'لا يوجد الكمية في المخزن',
  CustomTrans.endOrder: 'انهاء الطلب',
  CustomTrans.theInventory: 'المخزن',
  CustomTrans.sales: 'المبيعات',
  CustomTrans.addReturn: 'اضافة مرتجع',
  CustomTrans.enterTheQuantityYouWantToReturnFromThisProduct:
      'ادخل الكمية التي تريد ارجاعها من هذا المنتج',
  CustomTrans.valid: 'صالح',
  CustomTrans.expired: 'منتهي الصلاحية',
  CustomTrans.damaged: 'تالف',
  CustomTrans.manufacturerDefect: 'عيب تصنيع',
  CustomTrans.theRemainderIsCreditedToTheCustomer: 'المتبقى يضاف رصيد للعميل',
  CustomTrans.theRepresentativePaysCashToTheCustomer:
      'المندوب يسدد نقدي للعميل',
  CustomTrans.residualcalculationMethod: 'طريقة حساب المتبقي',
  CustomTrans.needToChooseBillFirst: 'اختر الفاتورة اولا',
  CustomTrans.ordersPaid: 'طلبات (الدفع)',
  CustomTrans.ordersProduct: 'طلبات (المنتج)',
  CustomTrans.statistics: 'الاحصائيات',
  CustomTrans.accepted: 'تم اعتماده',
  CustomTrans.done: 'تم استلامه',
  CustomTrans.denied: 'مرفوض',
  CustomTrans.intinerary: 'خط سير',
  CustomTrans.weeklyPlan: 'خط الأسبوع',
  CustomTrans.dayOFF: 'اجازه',
  CustomTrans.noPlan: 'لا يوجد خطه',
  CustomTrans.train: 'تدريب',
  CustomTrans.notificationSetting: 'اعدادت الاشعارات',
  CustomTrans.rangeOFNotification: 'مدى الاشعارات بالكم',
  CustomTrans.notifications: 'اشعارات',
  CustomTrans.title: "عنوان",
  CustomTrans.fromVacation: 'بداية الأجازة',
  CustomTrans.toVacation: 'نهاية الأجازة',
  CustomTrans.vacation: 'أجازة',
  CustomTrans.enterHistory: 'ادخل التاريخ',
  CustomTrans.cashTotal: 'الاجمالي',
  CustomTrans.category: 'الفئة',
  CustomTrans.count: 'العدد',
  CustomTrans.chitCash: 'شيت النقدية',
  CustomTrans.number: 'الرقم المسلسل',
  CustomTrans.storeMovement: 'المخزن',
  CustomTrans.movements: 'التحويلات',
  CustomTrans.chooseDevice: 'اختر الجهاز',
  CustomTrans.printe: 'طباعة',
  CustomTrans.remove: 'حذف',
  CustomTrans.wasTheProductSamplesDeliveredToTheCustomer:
      "تم تسليم عينات من المنتجات للعميل ؟",
  CustomTrans.decision: 'القرار',
  CustomTrans.add: 'أضف',
  CustomTrans.printerName: 'اسم الطابعة',
  CustomTrans.printerPassword: 'رقم السري للطابعة',
  CustomTrans.addInventory: 'اضافة جرد',
  CustomTrans.needToPickImageFirst: 'اختر الصورة أولا',
  CustomTrans.purposeOfVisit: 'غرض الزيارة',
  CustomTrans.editVisitPurpose: 'تعديل غرض الزياره',
  CustomTrans.unKnownDevices: 'أجهزة غير معروفة',
  CustomTrans.wallet: 'المحفظة',
  CustomTrans.walletCredit: 'رصيد المحفظة',
  CustomTrans.amount: 'المبلغ',
  CustomTrans.walletDeposit: 'ايداع محفظة',
  CustomTrans.withdrawFromWallet: 'سحب من المحفظة',
  CustomTrans.cashDeposit: 'ايداع كاش ',
  CustomTrans.depositUsingCheck: 'ايداع باستخدام الشيك ',
  CustomTrans.cashWithdrawal: 'سحب كاش',
  CustomTrans.checkNumber: 'رقم الشيك',
  CustomTrans.dueDate: 'تاريخ الاستحقاق',
  CustomTrans.call: 'اتصال',
  CustomTrans.sms: 'رسالة',
  CustomTrans.whatsapp: 'واتس اب',
  CustomTrans.doYouWantToGoToMaps: 'هل تريد الذهاب إلى الخرائط؟',
  CustomTrans.theNumberMustBeGreaterThanZero: 'الرقم يجب أن يكون أكبر من الصفر',
  CustomTrans.fastPay: 'دفع سريع',
  CustomTrans.fastPayExplain: 'هنا شرح التفاصيل الخاصة بالدفع السريع',
  CustomTrans.products: 'المنتجات',
  CustomTrans.endReturn: 'انهاء المرتجع',
  CustomTrans.writeNumber: 'اكتب رقم',
  CustomTrans.discountDetails: "تفاصيل الخصم",
  CustomTrans.offer: 'عرض',
  CustomTrans.discountforClient: 'خصم خاص للعميل',
  CustomTrans.removedFromTheCart: 'تم حذف المنتج من السله',
  CustomTrans.addedToTheCart: 'تم اضافة المنتج للسله',
  CustomTrans.addedToOrdersSuccessfully: 'تم اضافة الطلب بنجاح',
  CustomTrans.settingPrint: 'طابعات',
  CustomTrans.payTheAmountPaid:
      'يجب كنابة المبلغ المدفوع ويكون اقل من او يساوي الفاتورة',
  CustomTrans.selectPaymentType: 'اختر طريقة الدفع',
  CustomTrans.selectPaymentMethod: 'اختار طريقة الدفع',
  CustomTrans.indebtedness: 'المديونيات',
  CustomTrans.collections: 'التحصيلات',
  CustomTrans.quarterlyReport: 'التقرير الربع سنوي',
  CustomTrans.loginSuccess: 'تم تسجيل الدخول بنجاح',
  CustomTrans.logoutSuccess: 'تم تسجيل الخروج بنجاح',
  CustomTrans.paidByWallet: 'المدفوع من المحفظة',
  CustomTrans.paidInCash: 'المدفوع نقدا',
  CustomTrans.pleaseActivateLocation: 'يجب تفعيل تحديد الموقع',
  CustomTrans.locationPermission: ' تحديد الموقع',
  CustomTrans.returnHasBeenAddedSuccessfully: ' تمت إضافة المرتجع بنجاح',
  CustomTrans.covenant: 'العهده',
  CustomTrans.instructions: 'التعليمات',
  CustomTrans.canceled: 'ملغي',
  CustomTrans.shipmentNote: 'ملاحظات الشحنة',
  CustomTrans.chooseCancelReason: 'اختر سبب الالغاء',
  CustomTrans.waitingToRecord: 'في انتظار التسجيل',
  CustomTrans.addImage: 'أضف صوره',
  CustomTrans.policyNumber: 'رقم البوليصة',
  CustomTrans.shipmentDescription: 'وصف الشحنه',
  CustomTrans.notesOnTheShipment: 'ملاحظات على الشحنه',
  CustomTrans.customerName: 'اسم العميل',
  CustomTrans.supplierDetails: 'تفاصيل المورد',
  CustomTrans.prepaid: ' دفع مقدم',
  CustomTrans.delayedOrder: 'اوردر مؤجل',
  CustomTrans.orderDeliver: 'توصيل طلبات',
  CustomTrans.endWorkFirst: 'يجب انهاء العمل أولا',
  CustomTrans.doYouWantToContact: 'هل تريد الاتصال',
  CustomTrans.doYouWantToRemoveThisProductFromCart:
      "هل تريد إزالة هذا المنتج من سلة التسوق؟",
  CustomTrans.forgetPasswordWord: "لم تتذكر كلمة السر ؟",
  CustomTrans.forgetPasswordLine:
      "تم إرسال رمز التحقق إلى الايميل المسجل في التطبيق. الرجاء إدخال رمز التحقق.",
  CustomTrans.createPasswordLine: "اكتب كلمة المرور الجديدة لتسجيل الدخول",
  CustomTrans.off: "خصم",
  CustomTrans.reOrder: "إعادة طلب",
  CustomTrans.sellerRate: "قيم البائع",
  CustomTrans.rateTheProduct: "قيم االمنتج",
  CustomTrans.rateRep: "قيم المندوب",
  CustomTrans.selectDateAndTime: "اختر التاريخ والوقت",
  TabTypes.current.name: "الحاليه",
  TabTypes.past.name: "القديمة",

  PeriodType.Day60.name:"٦٠ يوم",  
  PeriodType.Day90.name :"٩٠ يوم",
  PeriodType.Other.name:"أخرى",

  CustomTrans.ok: 'موافق',
  CustomTrans.all_right: 'جميع الحقوق محفوظة ©',
  CustomTrans.our_values: 'قيمنا',
  CustomTrans.services: 'خدماتنا',
  CustomTrans.about_us: 'معلومات عنا',
  CustomTrans.branches: 'الفروع',
  CustomTrans.contact_us: 'تواصل معنا',
  CustomTrans.click_here: 'اضغط هنا',
  CustomTrans.startServiceAs: 'اطلب خدمة كـ',
  CustomTrans.guest: 'ضيف',
  CustomTrans.employee: 'موظف',
  CustomTrans.go: 'اذهب',
  CustomTrans.CompanyAddress: 'عنوان الشركة',
  CustomTrans.CustomerServices: 'خدمات العملاء',
  CustomTrans.Office: 'الإدارة',
  CustomTrans.find_us: 'حساباتنا',
  CustomTrans.more: 'المزيد',
  CustomTrans.website_full_version: 'نسخة الويب الكاملة',
  CustomTrans.privacy_policy: 'سياسة الخصوصية',
  CustomTrans.terms_and_cond: 'سياسات وشروط الاستخدام',
  CustomTrans.powered_by: 'مشغل بواسطة نيشان ®',
  CustomTrans.create_new_ticket: 'إنشاء تذكرة جديدة',
  CustomTrans.mobile: 'الجوال *',
  CustomTrans.send_verification: 'أرسل رمز التحقق بعد',
  CustomTrans.id: 'الرقم التعريفي / الإقامة *',
  CustomTrans.sorry_your_id: 'نأسف رقمك التعريفي/إقامتك ليس في سجلاتنا.',
  CustomTrans.verificationCode: 'رمز التحقق',
  CustomTrans.to_help_us:
      'لمساعدتنا في بناء اتصال آمن وموثوق مع الخدمات \n , يرجى إدخال البيانات بشكل صحيح ',
  CustomTrans.please_complete: 'يرجى إكمال البيانات لإرسال تذكرتك',
  CustomTrans.select_city: 'اختر مدينة *',
  CustomTrans.select_branch: 'حدد الفرع *',
  CustomTrans.select_category: 'اختر الفئة *',
  CustomTrans.details: 'التفاصيل',
  CustomTrans.select_attachment: 'حدد نوع الملحقات لرفعها',
  CustomTrans.agree_privacy_policy:
      'أوافق على الخصوصية والسياسة أيضًا شروط وأحكام.',
  CustomTrans.error: 'حدث خطأ ما',
  CustomTrans.required: 'هذا الحقل مطلوب',
  CustomTrans.this_is_not_email: 'هذا ليس بريد إلكتروني صالح',
  CustomTrans.please_enter_otp: 'الرجاء التأكد من إدخال رمز التأكيد',
  CustomTrans.press_to_record: 'اضغط لبدء التسجيل',
  CustomTrans.stop: 'توقف',
  CustomTrans.press_to_stop: 'اضغط لإيقاف التسجيل',
  CustomTrans.files: 'الملفات المرفقة',
  CustomTrans.all_fields_required: 'جميع الحقول مطلوبة',
  CustomTrans.full_name: 'الاسم الكامل',
  CustomTrans.success: 'تمت العملية بنجاح',
  CustomTrans.sendMail: 'إرسال إيميل',
  CustomTrans.mail: 'البريد الإلكتروني',
  CustomTrans.you_should_select_city:
      ' يجب عليك اختيار المدينة أولاً أو أن المدينة التي اخترتها لا تحتوي على فروع',
  CustomTrans.ourVission: 'رؤيتنا',
  CustomTrans.ourMission: 'مهمتنا',
  CustomTrans.secondes: 'ثانية',
  CustomTrans.createTicket: 'إنشاء بطاقة',
  CustomTrans.logout: 'تسجيل الخروج',
  CustomTrans.signUp: 'إنشاء حساب',
  CustomTrans.mobileEmail: 'البريد الإلكتروني / الجوال *',
  CustomTrans.mobileNumber: 'رقم الجوال *',
  CustomTrans.emailAddress: 'البريد الإلكتروني *',
  CustomTrans.selectNationality: 'اختر الجنسية *',
  CustomTrans.selectCity: 'اختر المدينة *',
  CustomTrans.selectRegion: 'اختر المنطقة *',
  CustomTrans.completeAsGuest: 'المتابعة كضيف',
  CustomTrans.pleaseEnter:
      'الرجاء إدخال رمز التأكيد المرسل على\nبريدك الإلكتروني ورقم جوالك',
  CustomTrans.enterVerificationCodeLine:
      'تم إرسال رمز التحقق إلى رقم الهاتف المسجل في التطبيق. الرجاء إدخال رمز التحقق.',
  CustomTrans.rememberMe: "تذكرني",
  CustomTrans.invitationCode: "كود الدعوة (اختياري)",
  CustomTrans.termsAndConditionsFirstLine: "من خلال الاستمرار، فإنك توافق على ",
  CustomTrans.terms: "سياسة الخصوصية",
  CustomTrans.and: "و",
  CustomTrans.conditions: "شروط الاستخدام",
  CustomTrans.registerLine: "قم بإنشاء حساب لاكتشاف ما هو جديد في مجتمعنا",
  CustomTrans.mainVerifyTitle:
      "أكمل بياناتك لتفعيل حسابك والاستفادة من جميع الميزات بسهولة وأمان مع تأكيد الهوية",
  CustomTrans.subscribe: "اشتراك",
  CustomTrans.promotions: "عروض ترويجية",
  CustomTrans.ads: "إعلانات",
  CustomTrans.requiredData: "بيانات مطلوبة",
  CustomTrans.completeData: "اكمل البيانات",
  CustomTrans.visitUsNow: 'زورنا الآن',
  CustomTrans.swipeLeft: 'اسحب لليسار',
  CustomTrans.scanQRCode: 'مسح رمز QR',
  CustomTrans.showDefaultCards: 'إظهار البطاقات الافتراضية',
  CustomTrans.bookService: 'خدمة الحجز',
  CustomTrans.orderTank: 'طلب لملئ الخزان',
  CustomTrans.cards: 'البطافات',
  CustomTrans.showBarcode: 'عرض الباركود',
  CustomTrans.addBalance: 'إضافة رصيد',
  CustomTrans.management: 'الإدارة',
  CustomTrans.transactions: 'الحركات',
  CustomTrans.holderType: 'نوع المالك',
  CustomTrans.holderName: 'اسم المالك',
  CustomTrans.holderMobile: 'جوال المالك',
  CustomTrans.holderEmail: 'إيميل المالك',
  CustomTrans.carType: 'نوع السيارة',
  CustomTrans.carStatus: 'حالة السيارة',
  CustomTrans.carModel: 'موديل السيارة',
  CustomTrans.lastUpdate: 'آخر تحديث',
  CustomTrans.edit: 'تعديل',
  CustomTrans.cardHistory: 'سجل البطاقة',
  CustomTrans.tank: 'النقليات',
  CustomTrans.myAccount: 'حسابي',
  CustomTrans.bookings: 'الحجوزات',
  CustomTrans.bookNow: 'احجز الآن',
  CustomTrans.orderNow: 'اطلب الآن',
  CustomTrans.startTrip: 'بدء الرحلة',
  CustomTrans.viewTrip: 'عرض الرحلة',
  CustomTrans.safetyReport: 'تقرير السلامة',
  CustomTrans.checkSafety: 'تحقق من السلامة',
  CustomTrans.redeemIt: 'استبدلها',
  CustomTrans.points: 'النقاط',
  CustomTrans.point: 'نقطة',
  CustomTrans.accountHistory: 'سجل الحساب',
  CustomTrans.carDetails: 'تفاصيل السيارة',
  CustomTrans.uploadCarImage: 'تحميل صورة السيارة',
  CustomTrans.itWillBeUsedFor:
      'سيتم استخدامه للتحقق عند الحاجة , ويفضل التقاط صورة لأمام السيارة ',
  CustomTrans.selectUserType: 'حدد نوع المستخدم',
  CustomTrans.serialNumber: 'معرف طراز السيارة',
  CustomTrans.vehicleColor: 'اللون',
  CustomTrans.selectCardColor: 'حدد لون البطاقة',
  CustomTrans.newCard: 'بطاقة جديدة',
  CustomTrans.personalDetails: 'تفاصيل الحامل',
  CustomTrans.create: 'إنشاء',
  CustomTrans.full_name_should_have_space:
      'يجب أن يحتوي الاسم الكامل على مسافة واحدة على الأقل بين الاسم الأول والأخير',
  CustomTrans.mobile_number_should_be_10_digits:
      'يجب أن يكون رقم الجوال 10 أرقام',
  CustomTrans.notificationTitle:
      'يتم عرض الإشعارات التي حدثت خلال آخر 30 يومًا',
  CustomTrans.vehicleData: "بيانات المركبة",
  CustomTrans.assignAsDefaultCard: 'تعيين كبطاقة افتراضية',
  CustomTrans.km: "كم",
  CustomTrans.ourWebsites: 'موقعنا',
  CustomTrans.fullVersion: ' النسخة الكاملة ',
  CustomTrans.about: "معلومات عنا",
  CustomTrans.menu: "القائمه",
  CustomTrans.delete: "حذف",
  CustomTrans.hey: "مرحبا",
  CustomTrans.saudiRiyal: "الريال السعودي",
  CustomTrans.time: "الوقت",
  CustomTrans.noTimeAvailable: "لا يوجد مواعيد",
  CustomTrans.noCardSelected: "لم يتم تحديد أي بطاقة",
  CustomTrans.mySelf: 'لنفسي',
  CustomTrans.other: 'للغير',
  CustomTrans.year: "سنه",
  CustomTrans.balance: "الرصيد",
  CustomTrans.packages: 'الحزم',
  CustomTrans.purchaseItNow: "شرائه الآن",
  CustomTrans.cardNotCreatedYet: "لم تنشئ بطاقة حتى الآن",
  CustomTrans.update: 'تعديل',
  CustomTrans.improveYourExperience: "تحسين تجربتك",
  CustomTrans.activation: "تفعيل",
  CustomTrans.redeemPoints: "استبدال النقاط",
  CustomTrans.currentPoints: "النقاط الحالية",
  CustomTrans.selectCard: "اختر البطاقة",
  CustomTrans.redeem: "يسترد",
  CustomTrans.addToTheSelectedCard: "أضف إلى البطاقة المحددة",
  CustomTrans.today: "اليوم",
  CustomTrans.rate: "معدل",
  CustomTrans.select: "اختر",
  CustomTrans.service: "خدمة",
  CustomTrans.book: "حجز",
  CustomTrans.description: "الوصف",
  CustomTrans.bookingTime: "ميعاد الحجز",
  CustomTrans.accessLine: "لا تمتلك صلاحيه الوصول لهذا القسم",
  CustomTrans.date: "التاريخ",
  CustomTrans.branch: "الفرع",
  CustomTrans.mustCreateNewCard: "يجب عليك إنشاء بطاقة جديدة أولاً",
  CustomTrans.cardDetails: "تفاصيل البطاقة",
  CustomTrans.pricePerLitre: "السعر للتر الواحد",
  CustomTrans.totalPayment: "المبلغ الإجمالي",
  CustomTrans.theNumberIsGreaterThanTheBalance: "الرقم اكبر من الرصيد ",
  CustomTrans.filter: "فلتر",
  CustomTrans.ownerName: "اسم المالك",
  CustomTrans.applySafety: "هل تم تطبيق قواعد السلامه ؟",
  CustomTrans.confirmStep: "تأكيد المهمه",
  CustomTrans.stepMessage: "هل انت متأكد من انهاء هذه المهمه؟",
  CustomTrans.needLogin: 'الرجاء تسجيل الدخول لاستخدام هذه الميزة',
  CustomTrans.needLoginHome: "يرجى تسجيل الدخول للاستفادة من مزايا التطبيق",
  CustomTrans.needLoginHomeButton: 'تسجيل/دخول',
  CustomTrans.needUpdateProfile: "يجب تحديث الحساب الشخصي",
  CustomTrans.propertyTypes: "أنواع الممتلكات",
  CustomTrans.districts: "المناطق",
  CustomTrans.facilities: "مرافق",
  CustomTrans.interfaces: "واجهات",
  CustomTrans.properties: "ملكيات",
  CustomTrans.clearFilter: "الغاء الفلتر",
  CustomTrans.blogs: "أخبارنا",
  CustomTrans.contractType: "نوع العقد",
  CustomTrans.contactAgent: "احجز الان",
  CustomTrans.sendLocation: "ارسال الموقع",
  CustomTrans.contact: "الاتصال",
  CustomTrans.advertiseNo: "رقم الإعلان",
  CustomTrans.chat: "محادثة",
  CustomTrans.items: "عقارات",
  CustomTrans.map: "خريطه",
  CustomTrans.showInMap: "الذهاب للخريطه",
  CustomTrans.leads: "القيادات",
  CustomTrans.interest: "الفائدة",
  CustomTrans.actions: "الإجراءات",
  CustomTrans.replyToLeads: "الرد على العملاء المحتملين",
  CustomTrans.updateInterest: "اهتمام التحديث",
  CustomTrans.employees: "الموظفون",
  CustomTrans.startSession: "بدء الجلسة",
  CustomTrans.employeesMenu: "شاشة الموظفين",
  CustomTrans.change: "التغيير",
  CustomTrans.to: "إلى",
  CustomTrans.units: "الوحدات",
  CustomTrans.type: "اكتب",
  CustomTrans.deposit: "الإيداع",
  CustomTrans.vision: "رؤية",
  CustomTrans.message: "رسالة",
  CustomTrans.auctions: "المزادات",
  BookType.Expired.name: "منتهية",
  BookType.New.name: "جديد",
  BookType.Rejected.name: "مرفوض",
  BookType.Done.name: "منتهي",
  BookType.CANCELD.name: "ملغي",
  InterestType.interest.name: "مهتم",
  InterestType.moreInterest.name: " مهتم جدا",
  CustomTrans.enjoyExtraProtection: 'استمتع بحماية إضافية وأمان تام لحسابك',
  CustomTrans.getAccessToAllFeatures:
      'احصل على وصول كامل لكل المزايا والخدمات الحصرية',
  CustomTrans.trackYourEarnings: 'سهولة في تتبع أرباحك وتقارير الأداء',
  CustomTrans.enhanceTrust: 'تعزيز الثقة بينك وبين الشبكة الخاصة بك',
  CustomTrans.pleaseEnterBasicInfo:
      'يرجى إدخال البيانات الأساسية لضمان تجربة استخدام أفضل وخدمات مخصصة لحسابك',
  CustomTrans.step1: 'الخطوة الأولى',
  CustomTrans.step2: 'الخطوة الثانية',
  CustomTrans.step3: 'الخطوة الثالثة',
  CustomTrans.firstName: 'الاسم الأول',
  CustomTrans.lastName: 'الاسم الأخير',
  CustomTrans.gender: 'الجنس',
  CustomTrans.country: 'الدولة',
  CustomTrans.basicData: 'البيانات الأساسية',
  CustomTrans.contactInformation: 'البيانات التواصل',
  CustomTrans.identityVerification: 'تأكيد الهوية',
  CustomTrans.reviewAndConfirmData: 'مراجعة وتأكيد البيانات',
  CustomTrans.identityVerificationTitle: 'تأكيد الهوية',
  CustomTrans.improveAccountSecurity:
      'لتحسين أمان حسابك وتوفير تجربة أفضل، نحتاج إلى التأكد من هويتك. يرجى متابعة الخطوات التالية:',
  CustomTrans.identityStep: 'خطوة الهوية',
  CustomTrans.verificationStep: 'خطوة التحقق',
  CustomTrans.confirmationStep: 'خطوة التأكيد',
  CustomTrans.captureIDPhoto: 'التقاط صورة الهوية',
  CustomTrans.ensureIDVisibility:
      'تأكد من أن بطاقة الهوية أو جواز السفر تظهر بالكامل في الصورة',
  CustomTrans.avoidShadowsAndReflections:
      'تجنب الظلال أو الانعكاسات التي قد تؤثر على وضوح النصوص',
  CustomTrans.takeFlatPhoto:
      'قم بتصوير البطاقة بشكل مستوي (أفقي أو رأسي) دون زوايا مائلة',
  CustomTrans.clearPhoto:
      'يجب أن تكون الصورة واضحة تماما بدون أي تشويش أو عوائق',
  CustomTrans.idCard: 'بطاقة الهوية',
  CustomTrans.passport: 'جواز السفر',
  CustomTrans.driversLicense: 'رخصة القيادة',
  CustomTrans.uploadIDInstructions: 'تعليمات رفع صورة بطاقة الهوية',
  CustomTrans.idPhotoUploadInstructions: 'تعليمات رفع صورة شخصية',
  CustomTrans.officialGovernmentID:
      'يجب أن تكون صورة هوية رسمية صادرة من جهة حكومية',
  CustomTrans.recentAndClearPhoto:
      'يجب أن تكون الصورة حديثة وواضحة، ولا يجب أن تكون نسخة ممسوحة ضوئياً أو نسخة من شاشة',
  CustomTrans.noFiltersOrEdits:
      'لا تستخدم فلاتر أو تعديلات قد تؤثر على وضوح الصورة',
  CustomTrans.fullFaceVisibility:
      'يجب أن تكون الصورة كاملة ومفهومة، ويجب أن يكون الوجه واضحاً ومكشوفاً بالكامل',
  CustomTrans.dataSubmittedSuccessfully:
      'تم إرسال بياناتك بنجاح! سيقوم فريقنا بمراجعة الملفات قريبًا. سنقوم بإعلامك عندما تتم الموافقة على الهوية',
  CustomTrans.yourFamilyHealthInYourHands: 'صحة عائلتك بين يديك',
  CustomTrans.keepTrackOfYourHealth: 'تابع صحتك مع حاسباتنا وتذكيراتنا',
  CustomTrans.symptomCheckersAndLibrary:
      'ستساعدك أدواتنا للتحقق من الأعراض ومكتبتنا على الشعور بالراحة',
  CustomTrans.toExploreOurAllTheFeatures: 'لاستكشاف جميع الميزات',
  CustomTrans.signInNow: 'تسجيل الدخول الآن',
  CustomTrans.ifYouDontHaveAnyAccount: 'إذا لم يكن لديك حساب. يرجى',
  CustomTrans.createANewOne: 'إنشاء حساب جديد.',
  CustomTrans.toCreateNewPasswordPlease: 'لإنشاء كلمة مرور جديدة يرجى',
  CustomTrans.followTheInstruction: 'اتباع التعليمات',
  CustomTrans.emailOrPhone: 'البريد الإلكتروني أو الهاتف',
  CustomTrans.show: 'إظهار',
  CustomTrans.getCode: 'الحصول على رمز',
  CustomTrans.or: 'أو',
  CustomTrans.agreeToTermAndConditions: 'أوافق على الشروط والأحكام',
  CustomTrans.signInWithGoogle: 'تسجيل الدخول باستخدام جوجل',
  CustomTrans.subscribeOurNewsletter: 'اشترك في نشرتنا الإخبارية',
  CustomTrans.iDontHaveAnAccountSignUp: 'ليس لدي حساب. سجل الآن',
  CustomTrans.iAlreadyHaveAnAccountLogin: 'لدي حساب بالفعل. تسجيل الدخول',
  CustomTrans.varification: 'التحقق',
  CustomTrans.pleaseEnterTheVerificationCodeAndExploreTheWorld:
      'يرجى إدخال رمز التحقق واستكشف العالم',
  CustomTrans.resendTheCode: 'إعادة إرسال الرمز',
  CustomTrans.thePasswordWasChangedSuccessfully: 'تم تغيير كلمة المرور بنجاح',
  CustomTrans.backToHome: 'العودة إلى الرئيسية',
  CustomTrans.resetPassword: 'إعادة تعيين كلمة المرور',
  CustomTrans.enterTheNewPassword: 'أدخل كلمة المرور الجديدة',
  CustomTrans.Areyousureyouwanttodeletehabittracking: 'هل أنت متأكد من حذف تتبع العادة؟',
  CustomTrans.englisg: 'انجليزي',
  CustomTrans.arabic: 'عربي',
  CustomTrans.logout: 'تسجيل الخروج',
   CustomTrans.location: 'الموقع',
   CustomTrans.precipitation: 'النبات',
   CustomTrans.humidity: 'الرطوبة',
   CustomTrans.windSpeed: 'سرعة الرياح',
   CustomTrans.dayForecast: 'معاينة الأيام القادمة',  
  
};
