import 'package:weather_app/data/const/enums.dart';
import 'package:get/get.dart';

import 'all_keys.dart';

Map<String, String> en = {
  CustomTrans.login: "Login",
  CustomTrans.createANewAccount: "create A New Account",
  CustomTrans.createNewAccount: "Create A New Account",
  CustomTrans.welcomeLine: "You must register to use the application",
  CustomTrans.welcome: "welcome",
  CustomTrans.phone: 'Phone Number',
  CustomTrans.write: "Write",
  CustomTrans.password: "password",
  CustomTrans.forgotYourPassword: "Forgot your password?",
  CustomTrans.youDontHaveAnAccount: "You Don't Have An Account",
  CustomTrans.alreadyHaveAnAccount: "Already have an account?",
  CustomTrans.send: "Send",
  CustomTrans.forgetScreenLine:
      "Don't worry, just type in your phone number and we'll send you a verification code.",
  CustomTrans.orBy: "OR",
  CustomTrans.codeVerification: "Code Verification",
  CustomTrans.otpScreenLine:
      "Enter the code that was sent to your phone number.",
  CustomTrans.editPhoneNumber: "Edit Phone Number",
  CustomTrans.resendMsg: "Resend Code",
  CustomTrans.confirmPassword: "Confirm Password",
  CustomTrans.crateNewPasswordScreenLine: "Type the new password to log in",
  CustomTrans.crateNewPassword: "Crate New Password",
  CustomTrans.choose: "Choose",
  CustomTrans.affiliateType: "AffiliateType",
  CustomTrans.next: "Next",
  CustomTrans.governorate: "Governorate",
  CustomTrans.city: "City",
  CustomTrans.productPromotionMethod: "Product promotion method",
  CustomTrans.dateOfBirth: "Date of Birth",
  CustomTrans.address: "Address",
  CustomTrans.yourWebsite: "Your Website",
  CustomTrans.iDontHaveAPersonalWebsite: "I don't have a personal website",
  CustomTrans.iAgreeToAffiliateProgram: "I agree to .'s Affiliate Program",
  CustomTrans.termsAndConditions: "Terms and Conditions",
  CustomTrans.name: "Name",
  CustomTrans.cancel: 'Cancel',
  CustomTrans.yourDataHasBeenSuccessfullyModified:
      'Your data has been successfully modified',
  CustomTrans.backToMain: 'back to main',
  CustomTrans.passwordChangedSuccessfully: 'Password changed successfully',
  CustomTrans.areYouSureYouWantToLogout: 'Are you sure you want to log out?',
  CustomTrans.signOut: 'sign out',
  CustomTrans.successOperation: 'operation accomplished successfully',
  CustomTrans.goMainPage: "GoMainPage",
  CustomTrans.somethingWentWrong: 'Oops something went wrong',
  CustomTrans.internalServerError: 'Internal server error',
  CustomTrans.badRequest: 'Bad request',
  CustomTrans.requestToAPIServerWasCancelled:
      'Request to API server was cancelled',
  CustomTrans.connectionTimeoutWithAPIServer:
      'Connection timeout with API server',
  CustomTrans.connectionToAPIServerFailedDueToInternetConnection:
      'Connection to API server failed due to internet connection',
  CustomTrans.receiveTimeoutInConnectionWithAPIServer:
      'Receive timeout in connection with API server',
  CustomTrans.sendTimeoutInConnectionWithAPIServer:
      'Send timeout in connection with API server',
  CustomTrans.resendCode: 'Resend Code',
  CustomTrans.fixedCommission: "fixed commission",
  CustomTrans.freeCommission: "Free Commission",
  CustomTrans.web: 'WebSite',
  CustomTrans.facebook: 'Facebook',
  CustomTrans.twitter: 'Twitter',
  CustomTrans.instagram: 'Instagram',
  CustomTrans.pinIsIncorrect: 'Pin is incorrect',
  CustomTrans.mustHaveValue: 'must have value',
  CustomTrans.wrongNumber: 'wrong number',
  CustomTrans.wrongConfirmedPassword: 'wrong confirmed password',
  CustomTrans.youMustChooseTheProvinceFirst:
      "You Must Choose The ${CustomTrans.governorate.tr} First",
  CustomTrans.wrongEmail: "Wrong Email",
  CustomTrans.email: "Email",
  CustomTrans.wrongWebSite: "Wrong Web-Site",
  CustomTrans.writePassword: 'Please enter your password',
  CustomTrans.writeName: 'please Write Name',
  CustomTrans.writePhone: 'please WritePhone',
  CustomTrans.showAll: 'ShowAll',
  CustomTrans.addToCart: 'Add To Cart',
  CustomTrans.price: 'Price',
  CustomTrans.commission: 'Commission',
  CustomTrans.writeDate: 'choose your Birth Date',
  CustomTrans.youMustChoose: 'need to choose',
  CustomTrans.pleaseWrite: 'please write',
  CustomTrans.goTo: 'Go To',
  CustomTrans.needToSignUpFirst: 'Need To Sign Up First',
  CustomTrans.mustChoose: 'You Must Choose',
  CustomTrans.mustWrite: 'You Must Write',
  CustomTrans.notification: 'Notifications',
  CustomTrans.confirm: "Confirm",
  CustomTrans.save: "Save",
  CustomTrans.favorite: 'tFavorite',
  CustomTrans.payment: 'Payment',
  CustomTrans.home: 'Home',
  CustomTrans.myOrder: 'orders',
  CustomTrans.setting: 'setting',
  CustomTrans.myProduct: 'Products',
  CustomTrans.buyWhenDeliveredCash: 'buy when delivered cash',
  CustomTrans.buyWithCreditCard: 'buy with credit card',
  CustomTrans.buyWithVodafoneCashWallet: 'buy with vodafone cash wallet',
  CustomTrans.supportCenter: "Support Center",
  CustomTrans.availableNow: "Available Now",
  CustomTrans.language: 'language',
  CustomTrans.categories: 'categories',
  CustomTrans.marks: 'marks',
  CustomTrans.whatDoYouSearchFor: 'what do you search for ?',
  CustomTrans.chooseTheItinerary: "Choose the itinerary",
  CustomTrans.notehasUploaded: "Note has Uploaded",
  CustomTrans.writeNotes: "Write Notes",
  CustomTrans.sendingNotes: "Sending Notes",
  CustomTrans.createItinerary: "CREATE ITINERARY",
  CustomTrans.createPlan: "Create Plan",
  CustomTrans.dailyReport: "Daily Report",
  CustomTrans.weeklyReport: "Weekly Report",
  CustomTrans.monthlyReport: "Monthly Report",
  CustomTrans.annualReport: "Annual Report",
  CustomTrans.pending: "pending",
  CustomTrans.bills: "Bills",
  CustomTrans.returns: "Returns",
  CustomTrans.receiveNotifications: "Receive notifications",
  CustomTrans.chooseAddress: "Choose Address",
  CustomTrans.listClientAddress: "List Client Address",
  CustomTrans.addNewLOCATION: "ADD NEW LOCATION",
  CustomTrans.multipleLocationOptions: "Multiple location options",
  CustomTrans.confirmReceiptOfThePayment: "Confirm receipt of the payment",
  CustomTrans.typeOfVisit: "Type of visit",
  CustomTrans.visit: "Visit",
  CustomTrans.inventory: "inventory",
  CustomTrans.chooseTypeOfVisit: "Choose Type of Visit",
  CustomTrans.addExpenses: "ADD EXPENSES",
  CustomTrans.reason: "Reason",
  CustomTrans.chooseClientsFirst: "Choose Clients First",
  CustomTrans.numberComplete: "Number complete",
  CustomTrans.thisDayIsaVacation: "this day is a vacation",
  CustomTrans.controlBoard: "CONTROL BOARD",
  CustomTrans.expenses: "EXPENSES",
  CustomTrans.noData: "No Data",
  CustomTrans.installment: "Installment",
  CustomTrans.chooseProductsFirst: "Choose Products First",
  CustomTrans.complete: "COMPLETE",
  CustomTrans.chooseReasonFirst: "Choose Reason First",
  CustomTrans.achieved: "Achieved",
  CustomTrans.workEndSuccessfully: "Work End Successfully",
  CustomTrans.thereIsNoAchievement: "There is no achievement",
  CustomTrans.theClientIsNotAvailable: "The client is not available",
  CustomTrans.chooseReason: "Choose Reason",
  CustomTrans.areYouSureYouWantToEndTask: "Are you sure you want to End Task ?",
  CustomTrans.enUA: "en_UA",
  CustomTrans.chooseDateFirst: "Choose Date First",
  CustomTrans.whyDoYouWantToPostponeTheVisitNow:
      "Why do you want to postpone the visit now?",
  CustomTrans.productMarketing: "Product Marketing",
  CustomTrans.arrive: "ARRIVE",
  CustomTrans.addReturns: "Add Returns",
  CustomTrans.addOrder: "Add Order",
  CustomTrans.addOperation: "Add Operation",
  CustomTrans.doYouWantToStartTaskNow: "Do you want  to start task now  ?",
  CustomTrans.companyDecisions: "Company decisions",
  CustomTrans.toyourCurrentLocation: "to your current location",
  CustomTrans.doYouWantChangeClientLocation:
      "Do you want change Client location",
  CustomTrans.cancelTask: "Cancel Task",
  CustomTrans.august: "August",
  CustomTrans.july: "July",
  CustomTrans.june: "June",
  CustomTrans.may: "May",
  CustomTrans.april: "April",
  CustomTrans.march: "March",
  CustomTrans.february: "February",
  CustomTrans.january: "January",
  CustomTrans.orders: "Orders",
  CustomTrans.notes: "Notes",
  CustomTrans.inProgress: "In Progress",
  CustomTrans.completed: "Completed",
  CustomTrans.chooseGovernmentFirst: "Choose Government First",
  CustomTrans.chooseCity: "Choose City",
  CustomTrans.chooseClientType: "choose client type",
  CustomTrans.clientType: "Client Type",
  CustomTrans.writePhoneNumber: "write phone number",
  CustomTrans.foundNoData: "Found No Data",
  CustomTrans.clientName: "client name",
  CustomTrans.reTurn: "RETURN",
  CustomTrans.pleaseChooseProductsYouWantToReturnAndTheWayOfReturns:
      "Please choose products you want to return and the way of returns",
  CustomTrans.areYouSureYouWantToReturnTheseProducts:
      "Are you sure you want to return these products ?",
  CustomTrans.numberOfMonths: "Number of months",
  CustomTrans.numberOfInstallments: "Number of installments",
  CustomTrans.clientList: "Client List",
  CustomTrans.errorTryAgain: "Error try again",
  CustomTrans.chooseClientName: "choose client name",
  CustomTrans.enterNewDate: "Enter new date",
  CustomTrans.whyYouWantCancelVisitNow: "Why you want cancel visit now ? ",
  CustomTrans.needToChooseClientFirst: "need to choose client first",
  CustomTrans.pleaseChooseClient: "please choose client",
  CustomTrans.cashReceipt: "Cash receipt",
  CustomTrans.newReturn: "New Return",
  CustomTrans.newOrder: "New Order",
  CustomTrans.search: "Search",
  CustomTrans.startWorkFirst: "Start work first",
  CustomTrans.chooseGovernmentAndCityFirst: "choose government and city first",
  CustomTrans.pleaseChooseCity: "please choose city",
  CustomTrans.government: "Government",
  CustomTrans.pleaseChooseGovernment: "please choose government",
  CustomTrans.chooseGovernment: "choose government",
  CustomTrans.pleaseEnableGpsAndPermissionAlwaysToStartWork:
      "please enable gps and permission always to start work",
  CustomTrans.endWork: "end work",
  CustomTrans.productsInfo: "PRODUCTS INFO",
  CustomTrans.removeProductsFromCart: "remove products from cart",
  CustomTrans.errorEcurePleaseTryAgain: "Error ecure please try again",
  CustomTrans.directions: "Directions",
  CustomTrans.packageSize: "Package size",
  CustomTrans.results: "Results",
  CustomTrans.ingredients: "Ingredients",
  CustomTrans.doses: "Doses",
  CustomTrans.indications: "Indications",
  CustomTrans.addClient: "Add Client",
  CustomTrans.addVisit: "Add Visit",
  CustomTrans.addInvoice: "Add Invoice",
  CustomTrans.visits: "Visits",
  CustomTrans.clients: "Clients",
  CustomTrans.store: "Store",
  CustomTrans.noNotification: "No Notification",
  CustomTrans.dismiss: "DISMISS",
  CustomTrans.checkOut: "Check out",
  CustomTrans.checkIn: "Check in",
  CustomTrans.areYouSureYouWantToCheckOut:
      "Are you sure you want to check out ?",
  CustomTrans.areYouSureYouWantToCheckIn: "Are you sure you want to check in ?",
  CustomTrans.createCustomVisits: "CREATE CUSTOM VISITS",
  CustomTrans.createWeekelyPlan: "CREATE WEEKLY PLAN",
  CustomTrans.managmentNotes: "MANAGMENT NOTES",
  CustomTrans.reports: "Reports",
  CustomTrans.yes: "YES",
  CustomTrans.no: "NO",
  CustomTrans.areYouSureYouWantToSignOut:
      " Are you sure you want to sign out  ?",
  CustomTrans.end: "end",
  CustomTrans.passwordNotMatch: "password not match",
  CustomTrans.newPassword: "new password",
  CustomTrans.sendAgain: "Send again",
  CustomTrans.completeAllFields: "Complete all fields",
  CustomTrans.enter4NumbersThatHaveBeenSentToYouOnThis:
      "Enter 4 numbers that have been sent to you on this",
  CustomTrans.activationMessage: "Activation message",
  CustomTrans.passwordNeedToMixBetweenLettersAndNumbers:
      "Password need to Mix between Letters and numbers",
  CustomTrans.errorTryConnectAgain: "error try Connect again",
  CustomTrans.tContinue: "CONTINUE",
  CustomTrans.toResetYourpassword: "to reset your password",
  CustomTrans.enterYourMobileNumberAndWeWillSendYouaCode:
      "Enter your mobile number and we will send you a code",
  CustomTrans.forgetPassword: "Forget Password",
  CustomTrans.forgotPassword: "Forgot password ?",
  CustomTrans.needPassword: "need password",
  CustomTrans.needPhoneNumber: "need phone number",
  CustomTrans.loginToGetStartedWithTheAppAndEnjoyAllTheFeartures:
      "login to get started with the app and enjoy all the feartures",
  CustomTrans.writeYourEmail: "write your email",
  CustomTrans.writeYourName: "write your name",
  CustomTrans.needToWriteYourName: "need to write your name",
  CustomTrans.profile: "Profile",
  CustomTrans.signIn: "Sign in",
  CustomTrans.errorConnection:
      "Error Connection Please Check the internet and try again",
  CustomTrans.changePasswordSuccessfully: "Change Password Successfully",
  CustomTrans.oldPassword: "old password",
  CustomTrans.pleaseWriteYourPassword: "please write your password",
  CustomTrans.settings: "Settings",
  CustomTrans.changePassword: "Change Password",
  CustomTrans.changeLanguage: "Change Language",
  CustomTrans.successfullyVisited: "Successfully visited",
  CustomTrans.installments: "installments",
  CustomTrans.enterReason: "Enter Reason",
  CustomTrans.collected: 'collected',
  CustomTrans.startWork: "start work",
  CustomTrans.createABusinessPlan: "Create a Business Plan",
  CustomTrans.administrativeNotes: "Administrative Notes",
  CustomTrans.resendMessage: "Resend Message",
  CustomTrans.enterYourActivationCodeAndAnActivationCodeWillBeSentToTheAccount:
      "Enter your activation code and an activation code will be sent to the account",
  CustomTrans.canNotRememberPassword: "Can't Remember Password",
  CustomTrans.andYouCanLogIn: "And you can log in",
  CustomTrans.enterEmail: "enter Email",
  CustomTrans.enterName: "Enter Name",
  CustomTrans.newClientInfo: 'New Client Info',
  CustomTrans.enterClientName: 'Enter Client Name',
  CustomTrans.enterClientType: 'Enter Client Type',
  CustomTrans.tCase: 'Case',
  CustomTrans.unComplete: 'not Complete',
  CustomTrans.cash: 'Cash',
  CustomTrans.code: 'Code',
  CustomTrans.quantity: "Quantity",
  CustomTrans.repName: 'Rep Name',
  CustomTrans.history: 'History',
  CustomTrans.deductionFromDept: 'Debt deduction',
  CustomTrans.merchandiseBalance: 'product',
  CustomTrans.cashBalance: 'cash',
  CustomTrans.paymentMethod: 'Payment Method',
  CustomTrans.total: 'Total',
  CustomTrans.paid: 'Paid',
  CustomTrans.remain: 'Remain',
  CustomTrans.totalOrders: "Total Orders",
  CustomTrans.totalOrdersAfter: 'Total orders after',
  CustomTrans.lE: "SAR",
  CustomTrans.imageNotFound: "image not found",
  CustomTrans.finished: 'finish',
  CustomTrans.started: 'start',
  CustomTrans.tNew: 'new',
  CustomTrans.appointments: 'appointments',
  CustomTrans.cart: 'cart',
  CustomTrans.lastOrder: 'Last Order',
  CustomTrans.lastBill: 'Last Bill',
  CustomTrans.operation: 'Operation',
  CustomTrans.visitPurpose: 'visit purpose',
  CustomTrans.visitSummary: 'visit summary',
  CustomTrans.newVisit: 'New Visit',
  CustomTrans.workStartSuccessfully: "Work Start Successfully",
  CustomTrans.totalBills: 'Total Bills',
  CustomTrans.pay: 'Pay',
  CustomTrans.payDirectlyToTheRepresentativeByGivingHimPaperMoney:
      'Pay directly to the representative by giving him paper money',
  CustomTrans.paymentByCheck: 'Payment by check',
  CustomTrans.writeCheck: 'Write a check',
  CustomTrans.noActionPlanToday: 'No action plan today',
  CustomTrans.hide: "hide",
  CustomTrans.totalPrice: 'Total price',
  CustomTrans.soldInsurance: 'Sold - Insurance',
  CustomTrans.soldInstallment: 'Sold - Installment',
  CustomTrans.soldCash: 'Sold - cash',
  CustomTrans.createAnInvoice: "Create an invoice",
  CustomTrans.createAnOrder: "Create an order",
  CustomTrans.sections: "Sections",
  CustomTrans.enterTheQuantityYouWantToAddFromThisProduct:
      'Enter the quantity you want to add from this product',
  CustomTrans.endPurchase: 'END PURCHASE',
  CustomTrans.continueOrder: 'CONTINUE ORDER',
  CustomTrans.makeANewOrderWithTheAmountOfMoneyOfReturnedProducts:
      'Make a new Order with the amount of money of returned products',
  CustomTrans.writingAChequeWithTheDemandedAmountOfMoneyAndHandingItToTheRep:
      "writing a cheque with the demanded amount of money and handing it to the Rep.",
  CustomTrans.oneTimePayment: "One time payment",
  CustomTrans.recieveCashInExchangeOfReturnedProducts:
      'Recieve cash in exchange of returned products',
  CustomTrans.recieveCash: 'Recieve cash',
  CustomTrans.moneyWillBePaidInFormerDepts:
      'Money will be paid in former depts',
  CustomTrans.payFromDept: 'Pay from dept',
  CustomTrans.afterReturn: 'After Return',
  CustomTrans.status: 'status',
  CustomTrans.offers: 'Offers',
  CustomTrans.getDiscount: 'get offers',
  CustomTrans.totalOffer: 'Total Offers',
  CustomTrans.totalAfter: "Total After",
  CustomTrans.gifts: 'Gifts',
  CustomTrans.thereIsNoQuantityInStock:
      'There is no this specific quantity in stock',
  CustomTrans.endOrder: 'endOrder',
  CustomTrans.theInventory: 'Inventory',
  CustomTrans.sales: 'Sales',
  CustomTrans.addReturn: 'Add Return',
  CustomTrans.enterTheQuantityYouWantToReturnFromThisProduct:
      'Enter The Quantity You Want To Return From This Product',
  CustomTrans.valid: 'valid',
  CustomTrans.expired: 'expired',
  CustomTrans.damaged: 'damaged',
  CustomTrans.manufacturerDefect: 'Manufacturer Defect',
  CustomTrans.theRemainderIsCreditedToTheCustomer:
      'The remainder is credited to the customer',
  CustomTrans.theRepresentativePaysCashToTheCustomer:
      'The representative pays cash to the customer',
  CustomTrans.residualcalculationMethod: 'Residual Calculation Method',
  CustomTrans.needToChooseBillFirst: 'Need To Choose Bill First',
  CustomTrans.ordersPaid: 'Order(Paid)',
  CustomTrans.ordersProduct: 'Order(Product)',
  CustomTrans.statistics: 'statistics',
  CustomTrans.accepted: 'accepted',
  CustomTrans.done: 'Done',
  CustomTrans.denied: 'denied',
  CustomTrans.intinerary: 'INTINERARY',
  CustomTrans.weeklyPlan: 'WEEKLY PLAN',
  CustomTrans.dayOFF: 'day off',
  CustomTrans.noPlan: 'no plan',
  CustomTrans.train: 'train',
  CustomTrans.notificationSetting: 'Notification Settting',
  CustomTrans.rangeOFNotification: 'Range of Notification',
  CustomTrans.notifications: 'Notifications',
  CustomTrans.title: "title",
  CustomTrans.fromVacation: 'from',
  CustomTrans.toVacation: 'to',
  CustomTrans.vacation: 'vacation',
  CustomTrans.enterHistory: 'choose data',
  CustomTrans.cashTotal: 'total',
  CustomTrans.category: 'Category',
  CustomTrans.count: 'Count',
  CustomTrans.chitCash: 'chit cash',
  CustomTrans.number: 'number',
  CustomTrans.storeMovement: 'store',
  CustomTrans.movements: 'movements',
  CustomTrans.chooseDevice: 'choose device',
  CustomTrans.printe: 'print',
  CustomTrans.remove: 'remove',
  CustomTrans.wasTheProductSamplesDeliveredToTheCustomer:
      'Was the product samples delivered to the customer?',
  CustomTrans.decision: 'decision',
  CustomTrans.add: 'add',
  CustomTrans.printerName: 'Printer Name',
  CustomTrans.printerPassword: 'printer Password',
  CustomTrans.addInventory: 'Add Inventory',
  CustomTrans.needToPickImageFirst: 'needToPickImageFirst',
  CustomTrans.purposeOfVisit: 'purpose of visit',
  CustomTrans.editVisitPurpose: 'Edit Visit Purpose',
  CustomTrans.unKnownDevices: 'Unknown Devices',
  CustomTrans.wallet: 'Wallet',
  CustomTrans.walletCredit: 'Credit',
  CustomTrans.amount: 'amount',
  CustomTrans.walletDeposit: 'wallet deposit',
  CustomTrans.withdrawFromWallet: 'Withdraw from wallet',
  CustomTrans.cashDeposit: 'cash deposit',
  CustomTrans.depositUsingCheck: 'Deposit using check',
  CustomTrans.cashWithdrawal: 'cash withdrawal',
  CustomTrans.checkNumber: 'Check Number',
  CustomTrans.dueDate: 'due date',
  CustomTrans.call: 'call',
  CustomTrans.sms: 'sms',
  CustomTrans.whatsapp: 'whatsapp',
  CustomTrans.doYouWantToGoToMaps: 'Do you want to go to Maps?',
  CustomTrans.theNumberMustBeGreaterThanZero:
      'The number must be greater than zero',
  CustomTrans.fastPay: 'fast pay',
  CustomTrans.fastPayExplain: 'fastPayExplain',
  CustomTrans.products: 'products',
  CustomTrans.endReturn: 'End Return',
  CustomTrans.writeNumber: 'write Number',
  CustomTrans.discountDetails: "Discount Details",
  CustomTrans.offer: 'offer',
  CustomTrans.discountforClient: 'discount for Client',
  CustomTrans.removedFromTheCart: 'remove from the cart',
  CustomTrans.addedToTheCart: 'added to the cart',
  CustomTrans.addedToOrdersSuccessfully: 'added To Orders Successfully',
  CustomTrans.settingPrint: 'Printers',
  CustomTrans.returnHasBeenAddedSuccessfully:
      'return has been added successfully',
  CustomTrans.payTheAmountPaid: 'Pay the amount paid',
  CustomTrans.selectPaymentType: 'select payment type',
  CustomTrans.selectPaymentMethod: 'select payment method',
  CustomTrans.indebtedness: 'indebtedness',
  CustomTrans.collections: 'collections',
  CustomTrans.quarterlyReport: 'Quarterly Report',
  CustomTrans.loginSuccess: 'Login successfully',
  CustomTrans.logoutSuccess: 'Logout Successfully',
  CustomTrans.paidByWallet: 'paid by wallet',
  CustomTrans.paidInCash: 'paid in cash',
  CustomTrans.pleaseActivateLocation: 'please activate location needed for app',
  CustomTrans.locationPermission: 'Location Permission',
  CustomTrans.covenant: 'covenant',
  CustomTrans.instructions: 'instructions',
  CustomTrans.canceled: 'canceled',
  CustomTrans.shipmentNote: 'shipment note',
  CustomTrans.chooseCancelReason: 'Choose Cancel Reason',
  CustomTrans.waitingToRecord: 'waiting to record',
  CustomTrans.addImage: 'add image',
  CustomTrans.policyNumber: 'Policy number',
  CustomTrans.shipmentDescription: 'shipment description',
  CustomTrans.notesOnTheShipment: 'Notes on the Shipment',
  CustomTrans.customerName: 'customer name',
  CustomTrans.supplierDetails: 'Supplier Details',
  CustomTrans.prepaid: 'prepaid',
  CustomTrans.delayedOrder: 'delayed order',
  CustomTrans.orderDeliver: 'order deliver',
  CustomTrans.endWorkFirst: 'need to end work first',
  CustomTrans.doYouWantToContact: 'do you want to contact',
  CustomTrans.doYouWantToRemoveThisProductFromCart:
      "do you want to remove this product from cart ?",
  CustomTrans.forgetPasswordWord: "Didn't you remember the password?",
  CustomTrans.forgetPasswordLine:
      "The verification code has been sent to the email registered in the application. Please enter the verification code.",
  CustomTrans.createPasswordLine: "Type your new password to log in",
  CustomTrans.off: "OFF",
  CustomTrans.reOrder: "re-order",
  CustomTrans.sellerRate: "Seller Rate",
  CustomTrans.rateTheProduct: "Rate the product",
  CustomTrans.rateRep: "Rep Rate",
  CustomTrans.selectDateAndTime: "Select date and time",
  TabTypes.current.name: "Current", 
  TabTypes.past.name: "Past",

  PeriodType.Day60.name : "60 Day",
PeriodType.Day90.name :"90 Day",
PeriodType.Other.name:"Other",

  CustomTrans.ok: 'Ok',
  CustomTrans.all_right: 'All rights reserved ©',
  CustomTrans.our_values: 'Our Values',
  CustomTrans.services: 'Services',
  CustomTrans.about_us: 'About Us',
  CustomTrans.branches: 'Branches',
  CustomTrans.contact_us: 'Contact Us',
  CustomTrans.click_here: 'Click Here',
  CustomTrans.startServiceAs: 'Start service as',
  CustomTrans.guest: 'Guest',
  CustomTrans.employee: 'Employee',
  CustomTrans.go: 'Go',
  CustomTrans.CompanyAddress: 'Company Address',
  CustomTrans.CustomerServices: 'Customer Services',
  CustomTrans.Office: 'Office',
  CustomTrans.find_us: 'Find Us',
  CustomTrans.more: 'More',
  CustomTrans.website_full_version: 'Website  Full version',
  CustomTrans.privacy_policy: 'Privacy & policy ',
  CustomTrans.terms_and_cond: 'Terms and Conditions',
  CustomTrans.powered_by: 'Powered by Nishan ®',
  CustomTrans.create_new_ticket: 'Create a new ticket',
  CustomTrans.mobile: 'Mobile *',
  CustomTrans.id: 'ID/Residence *',
  CustomTrans.send_verification: 'Send verification code again',
  CustomTrans.sorry_your_id: 'Sorry your ID/Residence not in our records.',
  CustomTrans.verificationCode: 'Verification code',
  CustomTrans.rememberMe: "Remember me",
  CustomTrans.invitationCode: "Invitation code (optional)",
  CustomTrans.termsAndConditionsFirstLine: "By continuing, you agree to the ",
  CustomTrans.terms: "Privacy Policy",
  CustomTrans.and: "And",
  CustomTrans.conditions: "Terms of Use",
  CustomTrans.registerLine:
      "Create an account to discover what's new in our community.",
  CustomTrans.to_help_us:
      'To help us build a secure and reliable connection with our services, please enter the data correctly',
  CustomTrans.mainVerifyTitle:
      "Complete your data to activate your account and benefit from all features easily and securely with identity verification",
  CustomTrans.subscribe: "Subscribe",
  CustomTrans.promotions: "Promotional Offers",
  CustomTrans.ads: "Ads",
  CustomTrans.requiredData: "Required Data",
  CustomTrans.completeData: "Complete Data",
  CustomTrans.please_complete: 'Please complete the data to\nsend your ticket',
  CustomTrans.select_city: 'Select City *',
  CustomTrans.select_branch: 'Select Branch *',
  CustomTrans.select_category: 'Select Category *',
  CustomTrans.details: 'Details',
  CustomTrans.select_attachment: 'Select attachment type to upload',
  CustomTrans.agree_privacy_policy:
      'I agree to the privacy & policy also terms & conditions.',
  CustomTrans.error: 'Something Happened!',
  CustomTrans.required: 'This Field is required!',
  CustomTrans.this_is_not_email: 'This is not an email!',
  CustomTrans.please_enter_otp: 'Please Enter OTP Code',
  CustomTrans.press_to_record: 'Press To Record',
  CustomTrans.stop: 'Stop',
  CustomTrans.press_to_stop: 'Press To Stop',
  CustomTrans.files: 'Attached Files',
  CustomTrans.all_fields_required: 'All Fields is required!',
  CustomTrans.full_name: 'Full Name',
  CustomTrans.success: 'Success',
  CustomTrans.sendMail: 'Send Mail',
  CustomTrans.mail: 'Email',
  CustomTrans.you_should_select_city:
      'You Should Select City First or the city you choose does not have branches!',
  CustomTrans.ourVission: 'Our Vision',
  CustomTrans.ourMission: 'Our Mission',
  CustomTrans.secondes: 'Secondes',
  CustomTrans.createTicket: 'Create Ticket',
  CustomTrans.logout: 'Logout',
  CustomTrans.signUp: 'Sign Up',
  CustomTrans.mobileEmail: 'Mobile/Email *',
  CustomTrans.fullName: 'Full Name *',
  CustomTrans.mobileNumber: 'Mobile Number *',
  CustomTrans.emailAddress: 'Email Address *',
  CustomTrans.selectNationality: 'Select Nationality *',
  CustomTrans.selectCity: 'Select City *',
  CustomTrans.selectRegion: 'Select district *',
  CustomTrans.completeAsGuest: 'Complete As Guest',
  CustomTrans.pleaseEnter:
      'Please enter the verification code sent\nto your mobile phone and e-mail',
  CustomTrans.enterVerificationCodeLine:
      'The verification code has been sent to the phone number registered in the application. Please enter the verification code.',
  CustomTrans.visitUsNow: 'Visit Us Now',
  CustomTrans.swipeLeft: 'Swipe Left',
  CustomTrans.scanQRCode: 'Scan QRCode',
  CustomTrans.showDefaultCards: 'Show Default Cards',
  CustomTrans.bookService: 'Book Service',
  CustomTrans.orderTank: 'Tank Filling Order',
  CustomTrans.cards: 'Cards',
  CustomTrans.showBarcode: 'Show QRCode',
  CustomTrans.addBalance: 'Add Balance',
  CustomTrans.management: 'Management',
  CustomTrans.transactions: 'Transactions',
  CustomTrans.holderType: 'Holder Type',
  CustomTrans.holderName: 'Holder Name',
  CustomTrans.holderMobile: 'Holder Mobile',
  CustomTrans.holderEmail: 'Holder Email',
  CustomTrans.carType: 'Car Type',
  CustomTrans.carStatus: 'Car Status',
  CustomTrans.carModel: 'Car Model',
  CustomTrans.lastUpdate: 'Last Update',
  CustomTrans.edit: 'Edit',
  CustomTrans.cardHistory: 'Card History',
  CustomTrans.tank: 'Tank',
  CustomTrans.myAccount: 'My Account',
  CustomTrans.bookings: 'Bookings',
  CustomTrans.bookNow: 'Book Now',
  CustomTrans.orderNow: 'Order Now',
  CustomTrans.startTrip: 'Start Trip',
  CustomTrans.viewTrip: 'View Trip',
  CustomTrans.safetyReport: 'Safety Report',
  CustomTrans.checkSafety: 'Check Safety',
  CustomTrans.redeemIt: 'Redeem It',
  CustomTrans.points: 'Points',
  CustomTrans.point: 'Point',
  CustomTrans.accountHistory: 'Account History',
  CustomTrans.carDetails: 'Car Details',
  CustomTrans.uploadCarImage: 'Upload Car Image',
  CustomTrans.itWillBeUsedFor:
      'It will be used for verification when needed, preferably taking a photo of the front of the car',
  CustomTrans.selectUserType: 'Select User Type',
  CustomTrans.serialNumber: 'Serial Number',
  CustomTrans.vehicleColor: 'Color',
  CustomTrans.selectCardColor: 'Select Card Color',
  CustomTrans.newCard: 'New Card',
  CustomTrans.personalDetails: 'Holder Details',
  CustomTrans.create: 'Create',
  CustomTrans.full_name_should_have_space:
      'Full Name Should Have Space Between First Name And Last Name',
  CustomTrans.notificationTitle:
      'The notifications that occurred during the last 30 days are displayed',
  CustomTrans.mobile_number_should_be_10_digits:
      'Mobile Number Should Be 10 Digits',
  CustomTrans.vehicleData: "Vehicle Data",
  CustomTrans.assignAsDefaultCard: 'Assign as Default Card',
  CustomTrans.km: "km",
  CustomTrans.ourWebsites: 'Our Website',
  CustomTrans.fullVersion: ' Full version ',
  CustomTrans.about: "about",
  CustomTrans.menu: "Menu",
  CustomTrans.delete: "Delete",
  CustomTrans.hey: "Hey",
  CustomTrans.saudiRiyal: "Saudi Riyal",
  CustomTrans.time: "Time",
  CustomTrans.noTimeAvailable: "no time available",
  CustomTrans.noCardSelected: "no card selected",
  CustomTrans.mySelf: 'myself',
  CustomTrans.other: 'other',
  CustomTrans.year: "year",
  CustomTrans.balance: 'Balance',
  CustomTrans.packages: 'Packages',
  CustomTrans.purchaseItNow: 'Purchase it now',
  CustomTrans.cardNotCreatedYet: "You haven't created a card yet",
  CustomTrans.update: 'Update',
  CustomTrans.improveYourExperience: "Improve your experience",
  CustomTrans.activation: "activation",
  CustomTrans.redeemPoints: "Redeem Points",
  CustomTrans.currentPoints: "Current Points",
  CustomTrans.selectCard: "Select Card",
  CustomTrans.redeem: "Redeem",
  CustomTrans.addToTheSelectedCard: "Add to the selected card",
  CustomTrans.today: "Today",
  CustomTrans.rate: "rate",
  CustomTrans.select: "Select",
  CustomTrans.service: "Service",
  CustomTrans.book: "Book",
  CustomTrans.description: "description",
  CustomTrans.bookingTime: "Booking time",
  CustomTrans.accessLine: "You don't have access to this section",
  CustomTrans.date: "Date",
  CustomTrans.branch: "branch",
  CustomTrans.mustCreateNewCard: "You must create a new card first",
  CustomTrans.cardDetails: "Card Details",
  CustomTrans.pricePerLitre: "price per litre",
  CustomTrans.totalPayment: "total payment",
  CustomTrans.theNumberIsGreaterThanTheBalance:
      "The number is greater than the balance",
  CustomTrans.filter: "Filter",
  CustomTrans.ownerName: "Owner Name",
  CustomTrans.applySafety: "apply safety rules?",
  CustomTrans.confirmStep: "Confirm Step",
  CustomTrans.stepMessage: "Are you sure you have completed this step?",
  CustomTrans.needLogin: 'Please login to use this feature',
  CustomTrans.needLoginHome: 'Please Login to access all app features',
  CustomTrans.needLoginHomeButton: 'Login/Sign Up',
  CustomTrans.needUpdateProfile: "The personal account must be updated",
  CustomTrans.propertyTypes: "property types",
  CustomTrans.districts: "districts",
  CustomTrans.facilities: "facilities",
  CustomTrans.interfaces: "interfaces",
  CustomTrans.properties: "properties",
  CustomTrans.clearFilter: "clear filter",
  CustomTrans.blogs: "blogs",
  CustomTrans.contractType: "contract type",
  CustomTrans.contactAgent: "contact agent",
  CustomTrans.sendLocation: "send location",
  CustomTrans.vision: "vision",
  CustomTrans.message: "message",
  CustomTrans.contact: "contact",
  CustomTrans.advertiseNo: "advertise number",
  CustomTrans.chat: "Chat",
  CustomTrans.items: "Items",
  CustomTrans.map: "map",
  CustomTrans.showInMap: "show in map",
  CustomTrans.leads: "leads",
  CustomTrans.interest: "interest",
  CustomTrans.actions: "actions",
  CustomTrans.replyToLeads: "reply To Leads",
  CustomTrans.updateInterest: "update Interest",
  CustomTrans.employees: "employees",
  CustomTrans.startSession: "start session",
  CustomTrans.employeesMenu: "Staff Screen",
  CustomTrans.change: "change",
  CustomTrans.to: "to",
  CustomTrans.units: "units",
  CustomTrans.type: "type",
  CustomTrans.deposit: "deposit",
  CustomTrans.auctions: "Auctions",
  BookType.Expired.name: "Expired",
  BookType.New.name: "New",
  BookType.Rejected.name: "Rejected",
  BookType.Done.name: "Done",
  BookType.CANCELD.name: "Canceled",
  InterestType.interest.name: "interest",
  InterestType.moreInterest.name: "more interest",
  CustomTrans.enjoyExtraProtection:
      'Enjoy extra protection and complete security for your account.',
  CustomTrans.getAccessToAllFeatures:
      'Get full access to all exclusive features and services.',
  CustomTrans.trackYourEarnings:
      'Easily track your earnings and performance reports.',
  CustomTrans.enhanceTrust: 'Enhance trust between you and your network.',
  CustomTrans.pleaseEnterBasicInfo:
      'Please enter the basic information to ensure a better user experience and personalized services for your account.',
  CustomTrans.step1: 'Step 1',
  CustomTrans.step2: 'Step 2',
  CustomTrans.step3: 'Step 3',
  CustomTrans.firstName: 'First Name',
  CustomTrans.lastName: 'Last Name',
  CustomTrans.gender: 'Gender',
  CustomTrans.country: 'Country',
  CustomTrans.basicData: 'Basic Data',
  CustomTrans.contactInformation: 'Contact Information',
  CustomTrans.identityVerification: 'Identity Verification',
  CustomTrans.reviewAndConfirmData: 'Review and Confirm Data',
  // ... other English translations ...
  CustomTrans.identityVerificationTitle: 'Identity Verification',
  CustomTrans.improveAccountSecurity:
      'To improve your account security and provide a better experience, we need to verify your identity. Please follow the following steps:',
  CustomTrans.identityStep: 'Identity Step',
  CustomTrans.verificationStep: 'Verification Step',
  CustomTrans.confirmationStep: 'Confirmation Step',
  CustomTrans.captureIDPhoto: 'Capture ID Photo',
  CustomTrans.ensureIDVisibility:
      'Ensure that the entire ID card or passport is visible in the photo.',
  CustomTrans.avoidShadowsAndReflections:
      'Avoid shadows or reflections that may obscure the text.',
  CustomTrans.takeFlatPhoto:
      'Take a photo of the card flat (horizontal or vertical) without tilting it.',
  CustomTrans.clearPhoto:
      'The photo should be clear and free of any blur or obstructions.',
  CustomTrans.idCard: 'ID Card',
  CustomTrans.passport: 'Passport',
  CustomTrans.driversLicense: 'Driver\'s License',
  CustomTrans.uploadIDInstructions: 'Upload ID Instructions',
  CustomTrans.idPhotoUploadInstructions: 'ID Photo Upload Instructions',
  CustomTrans.officialGovernmentID:
      'The photo must be an official government-issued ID',
  CustomTrans.recentAndClearPhoto:
      'The photo must be recent and clear, not a scanned copy or a screenshot.',
  CustomTrans.noFiltersOrEdits:
      'Do not use filters or edits that may affect the clarity of the photo.',
  CustomTrans.fullFaceVisibility:
      'The photo must be complete and clear, and the face must be fully visible.',
  CustomTrans.dataSubmittedSuccessfully:
      'Your data has been submitted successfully! Our team will review your files shortly. We will notify you when your identity is verified.',
  CustomTrans.yourFamilyHealthInYourHands:
      'Your family’s health within your hands',
  CustomTrans.keepTrackOfYourHealth:
      'Keep track of your health with our calculators and reminders',
  CustomTrans.symptomCheckersAndLibrary:
      'Our symptom checkers and library will keep your mind at ease',

  CustomTrans.toExploreOurAllTheFeatures: 'To Explore Our All The Features',
  CustomTrans.signInNow: 'Sign In Now',
  CustomTrans.ifYouDontHaveAnyAccount: 'If You Don’t Have Any Account. Please',
  CustomTrans.createANewOne: 'Create An New One.',
  CustomTrans.toCreateNewPasswordPlease: 'To Create New Password Please',
  CustomTrans.followTheInstruction: 'Follow The Instruction',
  CustomTrans.emailOrPhone: 'Email or Phone',
  CustomTrans.show: 'Show',
  CustomTrans.getCode: 'Get Code',
  CustomTrans.or: 'Or',
  CustomTrans.agreeToTermAndConditions: 'Agree To Term & Conditions',
  CustomTrans.signInWithGoogle: 'Sign In With Google',
  CustomTrans.subscribeOurNewsletter: 'Subscribe Our Newsletter',
  CustomTrans.iDontHaveAnAccountSignUp: 'I don’t have an account. Sign up',
  CustomTrans.iAlreadyHaveAnAccountLogin: 'I already have an account. Login',
  CustomTrans.varification: 'Varification',
  CustomTrans.pleaseEnterTheVerificationCodeAndExploreTheWorld:
      'Please Enter The Verification Code And Explore The World.',
  CustomTrans.resendTheCode: 'Resend the Code',
  CustomTrans.thePasswordWasChangedSuccessfully:
      'The password was changed successfully',
  CustomTrans.backToHome: 'Back to Home',
  CustomTrans.resetPassword: 'Reset Password',
  CustomTrans.enterTheNewPassword: 'Enter the new password',
  CustomTrans.Areyousureyouwanttodeletehabittracking: 'Are you sure you deleted Habit Breaker?',
 CustomTrans.arabic: 'Arabic',
 CustomTrans.englisg: 'English',
 CustomTrans.location: 'Location',
 CustomTrans.precipitation: 'Precipitation',
CustomTrans.humidity: 'Humidity',
CustomTrans.windSpeed: 'Wind Speed',
CustomTrans.dayForecast: '3 Day Forecast',

};
