name: Flutter CI + Firebase App Distribution - Weather App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-distribute:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ جلب الكود
      - uses: actions/checkout@v3

      # 2️⃣ تثبيت Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      # 3️⃣ جلب الحزم dependencies
      - run: flutter pub get

      # 4️⃣ تحليل الكود
      - run: flutter analyze

      # 5️⃣ تشغيل الاختبارات
      - run: flutter test --coverage

      # 6️⃣ عمل Build APK
      - run: flutter build apk --release

      # 7️⃣ رفع التطبيق على Firebase App Distribution
      - name: Distribute to Firebase
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app <1:1013606804464:android:8c5881b01983ab82fc4b35> \
          --groups "testers" \
          --token ${{ secrets.FIREBASE_TOKEN }}
